name: Cypress tests

on: [push]

jobs: 
  cypress-run:
    steps:
      name: Cypress run
      uses: cypress-io/github-action@v5.6.1
        with:
          build: npm run build
          start: npm start